baseURL: ""
languageCode: en-us
title: Maxwell Goisman
theme: gokarna


menu:
    main:
   #     - identifier: Tagslkj
    #      name: Tags
     #     url: /tags/
      #    weight: 60
 #       - identifier: Resume
  #        name: Resume
   #       url: /resume/
    #      weight: 50
   #     - identifier: Projects
    #      name: Projects
     #     url: /projects/
      #    weight: 40
     #   - identifier: Posts
      #    name: Posts
       #   url: /posts/
        #  weight: 30
        - identifier: About
          name: About
          url: /about/
          weight: 20
       # - identifier: Home
        #  name: Home
         # url: /home/
          #weight: 10
        - identifier: ChessScore
          name: ChessScoreagainstBen
          url: /chessscore/
          weight: 70