baseURL: "https://cosmicbanana.netlify.app"
languageCode: en-us
title: Maxwell Goisman 
theme: gokarna



params:
  description: "ASU Computer Science Major"
  CustomFooterHTML: ""
  Footer: "Maxwell Goisman"
  avatarURL: /img/affeastanding.png
  socialIcons: [
      {name = "email", url = "Maxickar@gmail.com"}
    ]


menu:
    main:
   #     - identifier: Tags
    #      name: Tags
     #     url: /tags/
      #    weight: 60
 #       - identifier: Resume
  #        name: Resume
   #       url: /resume/
    #      weight: 50
        - identifier: Projects
          name: Projects
          url: /projects/
          weight: 30
        - identifier: About
          name: About
          url: /about/
          weight: 20
        - identifier: Home
          name: Home
          url: /home/
          weight: 10
        - identifier: ChessScore
          name: ChessScoreagainstBen
          url: /chessscore/
          weight: 70